import { createAsyncThunk, createSlice } from '@reduxjs/toolkit'
import { RootState } from '@/providers/store'
import { fetchExchangeList } from './homeApi'

export interface HomeState {
  exchangeList: any[]
}

const initialState: HomeState = {
  exchangeList: []
}

export const fetchExchangeListAsync = createAsyncThunk('home/fetchExchangeList', async () => {
  const response = await fetchExchangeList()
  return response.data
})

export const homeSlice = createSlice({
  name: 'home',
  initialState,
  reducers: {
    setExchangeListAct: (state, action) => {
      state.exchangeList = action.payload
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchExchangeListAsync.pending, (state) => {
        console.log(123123, 'loading')
      })
      .addCase(fetchExchangeListAsync.fulfilled, (state, action) => {
        state.exchangeList = action.payload
      })
  }
})

export const { setExchangeListAct } = homeSlice.actions

export const selectExchangeList = (state: RootState) => state.home.exchangeList

export default homeSlice.reducer
